# Generated by Django 5.0.4 on 2024-07-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('middle_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('name_extension', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('zip_code', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('date_of_birth', models.CharField(max_length=100, null=True)),
                ('place_of_birth', models.CharField(max_length=100, null=True)),
                ('sex', models.CharField(max_length=100, null=True)),
                ('civil_status', models.CharField(max_length=100, null=True)),
                ('height', models.CharField(max_length=100, null=True)),
                ('weight', models.CharField(max_length=100, null=True)),
                ('blood_type', models.CharField(max_length=100, null=True)),
                ('citizenship', models.CharField(max_length=100, null=True)),
                ('mothers_first_name', models.CharField(max_length=100, null=True)),
                ('mothers_middle_name', models.CharField(max_length=100, null=True)),
                ('mothers_last_name', models.CharField(max_length=100, null=True)),
                ('father_first_name', models.CharField(max_length=100, null=True)),
                ('father_middle_name', models.CharField(max_length=100, null=True)),
                ('father_last_name', models.CharField(max_length=100, null=True)),
                ('spouses_surname', models.CharField(max_length=100, null=True)),
                ('spouses_middle_name', models.CharField(max_length=100, null=True)),
                ('spouses_last_name', models.CharField(max_length=100, null=True)),
                ('gsis_id_no', models.CharField(max_length=100, null=True)),
                ('pagibig_id_no', models.CharField(max_length=100, null=True)),
                ('philhealth_no', models.CharField(max_length=100, null=True)),
                ('sss_no', models.CharField(max_length=100, null=True)),
                ('tin_no', models.CharField(max_length=100, null=True)),
                ('agency_employee_no', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
