# Generated by Django 5.0.4 on 2024-07-09 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='spouses_last_name',
            new_name='spouses_first_name',
        ),
    ]
